### ISSUE TITLE
Error: Empty position list

### ISSUE THREAD

**Issue by danwani** [chesner/bf2csv#2]
I get the following issue when running the `npm run cli` command.  I have tried this on both windows and mac, and with multiple Blockfolio tokens.  Blockfolio seems to give me a different token each time settings is opened, is this expected?  The total token length is 96 characters, the first 32 remain constant, the last 64 change.  My guess is the first 32 are the device ID - I've tried using just this section also, but get the same error.  I'm running node v6.11.1.  I didn't see a specific version in the `package.json`.

> bf2csv@0.0.1 cli C:\node\bf2csv
> cross-env NODE_ENV=cli babel-node ./src/cli.js "<BF-token>"

Error: Empty position list, did you specify the correct token?
    at Object._callee2$ (C:/node/bf2csv/src/lib/blockfolio.js:45:11)
    at tryCatch (C:\node\bf2csv\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node\bf2csv\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node\bf2csv\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\node\bf2csv\src\lib\blockfolio.js:133:191)
    at C:\node\bf2csv\src\lib\blockfolio.js:133:361
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by ghost** [comment]
I got the same error when using the github website version: Error: Empty position list, did you specify the correct token? 

My token is correct. Any clue why this happens?

**Comment by danwani** [comment]
It's been a while since I looked at this - almost a year it seems!  From memory I think what happened was that Blockfolio changed their token to a more dynamic style designed to just work with their app, not intended for use elsewhere.  I never got this working.
